BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.userLogout, name='logout'),
    path('home/', views.BlogListView.as_view(), name='blog_list'),
    path('home/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('comment/like/<int:comment_id>/', views.like_comment, name='like_comment'),
    path('home/tag/<slug:slug>/', views.tagged, name='tagged'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from taggit.managers import TaggableManager

class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogs')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.slug])

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.blog.title}'
    def total_likes(self):
        return self.likes.count()

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Enter your comment here...'}),
        }

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, DetailView
from django.contrib import messages
from .models import Blog, Comment
from django.db.models import Q
# from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.shortcuts import get_object_or_404
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from taggit.models import Tag


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    blogs = Blog.objects.filter(tags=tag)

    return render(request, 'blog/tagged.html', {
        'tag': tag,
        'blogs': blogs
    })

class BlogListView(ListView):
    model = Blog
    paginate_by = 5
    context_object_name = 'blog'
    template_name = 'blog/blog_list.html'


def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    tags = blog.tags.all()
    comments = blog.comments.all()
    new_comment = None

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.blog = blog
                new_comment.user = request.user
                new_comment.save()
                return redirect('blog:blog_detail', slug=slug)
        else:
            return redirect('login')
    else:
        comment_form = CommentForm()

    return render(request, 'blog/blog_detail.html', {
        'blog': blog,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'tags': tags,
    })

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('blog:blog_list')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome, {username}!")
                return redirect('blog:blog_list')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    
    return render(request, 'registration/login.html', {'form': form})

def userLogout(request):
    logout(request)
    return redirect('login')



# def search(request):
#     query = request.GET.get('q')
#     if query:
#         search_vector = SearchVector('title', 'content', config='english')
#         search_query = SearchQuery(query)
#         blogs = Blog.objects.annotate(
#             search=search_vector,
#             rank=SearchRank(search_vector, search_query),
#             trigram=TrigramSimilarity('title', query),
#         ).filter(Q(rank__gte=0.3) | Q(trigram__gt=0.1)).order_by('-rank', '-trigram')
#     else:
#         blogs = Blog.objects.none()
#     return render(request, 'blog/search_results.html', {'blogs': blogs, 'query': query})

2

def like_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    return redirect('blog:blog_detail', slug=comment.blog.slug)

blog/templates/base_generic.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notes on Duke Ellington</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: sans-serif;
        }
        .post-container {
            padding: 20px;
        }
        .post-title {
            font-size: 24px;
            font-weight: bold;
        }
        .post-meta {
            font-size: 14px;
            color: #888;
            margin-bottom: 10px;
        }
        .post-content {
            margin-bottom: 20px;
        }
        .sidebar {
            background-color: #f5f5f5;
            padding: 20px;
        }
        .sidebar-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .sidebar-content {
            margin-bottom: 20px;
        }
        .share-button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
{%block content%}
{%endblock content%}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
    <div class="container ">
       
    <div class="blog-post">
        <h2>{{ blog.title }}</h2>
        <p class="blog-post-meta">Published {{ blog.created_at|date:"M. d, Y, H:i a" }} by {{ blog.author }}</p>
        <p>{{ blog.content }}</p>
    </div>
    <br>
    <!-- Display tags -->
    <div class="blog-tags">
        <h4>Tags:</h4>
        <ul>
            {% for tag in tags %}
        <a href="{% url 'blog:tagged' tag.slug %}"> #{{ tag.name }}</a>
            {% endfor %}
        </ul>
    </div>
    <hr>

    <div class="comments-section">
        <h3>Comments</h3>

        {% if comments %}
            <ul>
                {% for comment in comments %}
                <li>
                    <p>{{ comment.content }}</p>
                    <p class="comment-meta">
                        <small>{{ comment.user.username }} - {{ comment.created_at|date:"M. d, Y, H:i a" }}</small>
                        <span class="likes">
                            <a href="{% url 'blog:like_comment' comment.id %}">Like</a> ({{ comment.total_likes }})
                        </span>
                    </p>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No comments yet.</p>
        {% endif %}
    </div>

    <hr>

    <div class="comment-form">
        <h3>Leave a comment</h3>
        {% if user.is_authenticated %}
            <form method="post" >
                {% csrf_token %}
                <textarea name="content" rows="4" class="form-control" placeholder="Enter your comment here"></textarea>
                <button type="submit" class="btn btn-primary mt-2">Submit</button>
            </form>
        {% else %}
            <p>You must be <a href="{% url 'login' %}">logged in</a> to comment.</p>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}
{%block content%}
    <div class="container">
        {% for data in blog%}
        <div class="row">
            <div class="col-md-8">
                <div class="post-container">
                    <a href="{{data.slug}}"><h1 class="post-title">{{data.title}}</h1></a>
                    <div class="post-meta">Published {{ data.created_at|date:"M. d, Y, H:i a" }} by {{ data.author }}</div>
                    <div class="post-content">
                        {{data.content}}
                       
                    </div>
                    {%for tag in data.tags.all%}
                    <a href="{% url 'blog:tagged' tag.slug %}"> #{{ tag.name }}</a>
                    {%endfor%}
                    <br>    
                    <button class="share-button">Share this post</button>
                </div>
            </div>
            <div class="col-md-4">
                <div class="sidebar">
                    <h2 class="sidebar-title">{{data.title}}</h2>
                    <div class="sidebar-content">
                        This is my blog.
                    </div>
                </div>
            </div>
        </div>
        
        {%endfor%}
    </div>

    {% if is_paginated %}
    <div>
        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
        </div>
    </div>
{% endif %}

    {%endblock content%}

blog/templates/blog/search_results.html
{% extends "base_generic.html" %}

{% block content %}
<div class="blog-post">
    <h2>{{ blog.title }}</h2>
    <p class="blog-post-meta">Published {{ blog.created_at|date:"M. d, Y, H:i a" }} by {{ blog.author }}</p>
    <p>{{ blog.content }}</p>
    <p><a href="#">Share this post</a></p>
</div>

<hr>

<div class="comments-section">
    <h3>Comments</h3>

    {% if blog.comments.exists %}
        <ul>
            {% for comment in blog.comments.all %}
            <li>
                <p>{{ comment.content }}</p>
                <p class="comment-meta">
                    <small>{{ comment.user.username }} - {{ comment.created_at|date:"M. d, Y, H:i a" }}</small>
                    <span class="likes">
                        <a href="{% url 'blog:like_comment' comment.id %}">Like</a> ({{ comment.likes.count }})
                    </span>
                </p>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments yet.</p>
    {% endif %}
</div>

<hr>

<div class="comment-form">
    <h3>Leave a comment</h3>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            <textarea name="content" rows="4" class="form-control" placeholder="Enter your comment here"></textarea>
            <button type="submit" class="btn btn-primary mt-2">Submit</button>
        </form>
    {% else %}
        <p>You must be <a href="{% url 'blog:login' %}">logged in</a> to comment.</p>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/tagged.html
{% extends "base_generic.html" %}

{% block content %}
<div class="tagged-posts">
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    <ul>
        {% for blog in blogs %}
        <li>
            <a href="{% url 'blog:blog_detail' blog.slug %}">{{ blog.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}